#include: package:pedantic/analysis_options.1.8.0.yaml;
include: package:effective_dart/analysis_options.1.2.0.yaml
analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: true

#linter:
#  rules:
#    - annotate_overrides
#    - await_only_futures
#    - camel_case_types
#    - cancel_subscriptions
#    - close_sinks
#    - comment_references
#    - constant_identifier_names
#    - control_flow_in_finally
#    - empty_statements